### ISSUE TITLE
Map interia causes canvas offset

### ISSUE THREAD

**Issue by MattFerraro** [CartoDB/Leaflet.CanvasLayer#6] opened 2014-07-31 22:24 UTC
Right in the example:
http://cartodb.github.io/Leaflet.CanvasLayer/example.html

At first the red dot is centered just south of Ghana. If you tug the map to the right such that its inertia carries it off to right, the canvas layer seems to move to the right twice as fast. When the map comes to rest again, the red dot is centered below Cameroon instead of Ghana

If you pan the map just at tiny bit (or zoom in or out), it causes the canvas to be centered correctly again below Ghana.

Expected behavior is for the red dot to be centered below Ghana no matter the pan

**Comment by syntagmatic** [comment] 2015-03-12 19:10
Duplicate of #7

**Comment by javisantana** [comment] 2015-03-13 08:04
This is a known problem, I'm waiting for a leaflet release in order to either do another hack (https://github.com/CartoDB/Leaflet.CanvasLayer/blob/gh-pages/leaflet_canvas_layer.js#L74) or propose them a new event to listen for real map movements

**Comment by fdansv** [comment] 2015-05-06 09:00
This is now solved by #13

**Closed as completed by fdansv** 2015-05-06 09:00 UTC
